services:
  database:
    image: postgres:16
    container_name: postgres_node_api_bookstore
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: node_api_bookstore
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=api_bookstore
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:
